/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#eae7e7",
        "primary-fixed": "#c7eade",
        "on-tertiary-container": "#e68167",
        "on-background": "#1b1c1c",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container": "#f0eded",
        "surface-bright": "#fcf9f8",
        "tertiary-fixed": "#ffdbd2",
        "secondary-fixed-dim": "#aec9eb",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#2f4965",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#d1e4ff",
        "inverse-primary": "#abcec2",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffb4a2",
        "surface-tint": "#45655b",
        "outline": "#717975",
        "error": "#ba1a1a",
        "inverse-surface": "#303030",
        "on-secondary-fixed": "#001d35",
        "outline-variant": "#c1c8c4",
        "surface-container-low": "#f6f3f2",
        "secondary-container": "#c2dcff",
        "inverse-on-surface": "#f3f0f0",
        "background": "#fcf9f8",
        "on-tertiary-fixed": "#3c0800",
        "primary": "#02241d",
        "surface-container-highest": "#e4e2e1",
        "on-surface-variant": "#414846",
        "on-tertiary-fixed-variant": "#7b2e1a",
        "on-surface": "#1b1c1c",
        "on-primary-fixed": "#002019",
        "on-primary-container": "#82a499",
        "surface-dim": "#dcd9d9",
        "tertiary": "#420900",
        "surface": "#fcf9f8",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#2d4d44",
        "secondary": "#47607e",
        "tertiary-container": "#621c0a",
        "primary-container": "#1a3a32",
        "primary-fixed-dim": "#abcec2",
        "surface-variant": "#e4e2e1",
        "on-secondary-container": "#47617e"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "lg": "48px",
        "xs": "4px",
        "sm": "12px",
        "xl": "80px",
        "base": "8px",
        "md": "24px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-md": ["Sarabun", "sans-serif"],
        "label-sm": ["Courier Prime", "Sarabun", "sans-serif"],
        "headline-lg-mobile": ["Sarabun", "sans-serif"],
        "label-md": ["Courier Prime", "Sarabun", "sans-serif"],
        "body-lg": ["Sarabun", "sans-serif"],
        "headline-md": ["Sarabun", "sans-serif"],
        "display-lg": ["Sarabun", "sans-serif"],
        "headline-lg": ["Sarabun", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.7", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "700" }],
        "display-lg": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
